apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fileshare
spec:
  rules:
    - host: minikub-internal.ua
      http:
        paths:
          - backend:
              serviceName: fileshare
              servicePort: 80
